version: '3.9'

services:
  #Nodejs application
  api:
    #container_name: nodejs_api
    build: .
    ports:
     - 3000:3000
    volumes:
      - .:/home/student/getting-started-app
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./conf.d:/etc/nginx/conf.d
  #   depends_on:
  #     - api
  #   ports:
  #     - 3000:3000
